### ISSUE TITLE
Range Calendar does not obey rowHeight

### ISSUE THREAD

**Issue by thomassuckow** [clauderic/react-infinite-calendar#148]
The Range Calendar does not render correctly when rowHeight is set

![screen shot 2017-10-24 at 8 12 38 am](https://user-images.githubusercontent.com/3100037/31951495-29a9aee4-b893-11e7-8f5d-5bfd4169d026.png)

**Comment by thomassuckow** [comment]
This seems to help:

```css
.Cal__Day__range.Cal__Day__selected.Cal__Day__start:after, .Cal__Day__range.Cal__Day__selected.Cal__Day__end:after {
  height: 100%;
  margin-top: -33.333%;
}
```

But I am noticing this appears to assume you provide your own stylesheet if you tweak rowHeight. So I'll close this.
